/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as AddRouteImport } from './routes/add'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReelsIndexRouteImport } from './routes/reels.index'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as ReelsReelIdRouteImport } from './routes/reels.$reelId'
import { Route as BlogsBlogIdRouteImport } from './routes/blogs.$blogId'
import { Route as CatalogCourseCourseIdRouteImport } from './routes/catalog.course.$courseId'
import { Route as CatalogAuthorAuthorIdRouteImport } from './routes/catalog.author.$authorId'

const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsIndexRoute = ReelsIndexRouteImport.update({
  id: '/reels/',
  path: '/reels/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsReelIdRoute = ReelsReelIdRouteImport.update({
  id: '/reels/$reelId',
  path: '/reels/$reelId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogIdRoute = BlogsBlogIdRouteImport.update({
  id: '/$blogId',
  path: '/$blogId',
  getParentRoute: () => BlogsRoute,
} as any)
const CatalogCourseCourseIdRoute = CatalogCourseCourseIdRouteImport.update({
  id: '/catalog/course/$courseId',
  path: '/catalog/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogAuthorAuthorIdRoute = CatalogAuthorAuthorIdRouteImport.update({
  id: '/catalog/author/$authorId',
  path: '/catalog/author/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add': typeof AddRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/authors': typeof AuthorsRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/reels/$reelId': typeof ReelsReelIdRoute
  '/catalog/': typeof CatalogIndexRoute
  '/reels/': typeof ReelsIndexRoute
  '/catalog/author/$authorId': typeof CatalogAuthorAuthorIdRoute
  '/catalog/course/$courseId': typeof CatalogCourseCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add': typeof AddRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/authors': typeof AuthorsRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/reels/$reelId': typeof ReelsReelIdRoute
  '/catalog': typeof CatalogIndexRoute
  '/reels': typeof ReelsIndexRoute
  '/catalog/author/$authorId': typeof CatalogAuthorAuthorIdRoute
  '/catalog/course/$courseId': typeof CatalogCourseCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add': typeof AddRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/authors': typeof AuthorsRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/reels/$reelId': typeof ReelsReelIdRoute
  '/catalog/': typeof CatalogIndexRoute
  '/reels/': typeof ReelsIndexRoute
  '/catalog/author/$authorId': typeof CatalogAuthorAuthorIdRoute
  '/catalog/course/$courseId': typeof CatalogCourseCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add'
    | '/admin/leads'
    | '/authors'
    | '/blogs'
    | '/favorites'
    | '/profile'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/blogs/$blogId'
    | '/reels/$reelId'
    | '/catalog/'
    | '/reels/'
    | '/catalog/author/$authorId'
    | '/catalog/course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add'
    | '/admin/leads'
    | '/authors'
    | '/blogs'
    | '/favorites'
    | '/profile'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/blogs/$blogId'
    | '/reels/$reelId'
    | '/catalog'
    | '/reels'
    | '/catalog/author/$authorId'
    | '/catalog/course/$courseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add'
    | '/admin/leads'
    | '/authors'
    | '/blogs'
    | '/favorites'
    | '/profile'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/blogs/$blogId'
    | '/reels/$reelId'
    | '/catalog/'
    | '/reels/'
    | '/catalog/author/$authorId'
    | '/catalog/course/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddRoute: typeof AddRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AuthorsRoute: typeof AuthorsRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  ProfileRoute: typeof ProfileRoute
  PurchasesRoute: typeof PurchasesRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  ReelsReelIdRoute: typeof ReelsReelIdRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  ReelsIndexRoute: typeof ReelsIndexRoute
  CatalogAuthorAuthorIdRoute: typeof CatalogAuthorAuthorIdRoute
  CatalogCourseCourseIdRoute: typeof CatalogCourseCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels/': {
      id: '/reels/'
      path: '/reels'
      fullPath: '/reels/'
      preLoaderRoute: typeof ReelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels/$reelId': {
      id: '/reels/$reelId'
      path: '/reels/$reelId'
      fullPath: '/reels/$reelId'
      preLoaderRoute: typeof ReelsReelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$blogId': {
      id: '/blogs/$blogId'
      path: '/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/catalog/course/$courseId': {
      id: '/catalog/course/$courseId'
      path: '/catalog/course/$courseId'
      fullPath: '/catalog/course/$courseId'
      preLoaderRoute: typeof CatalogCourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/author/$authorId': {
      id: '/catalog/author/$authorId'
      path: '/catalog/author/$authorId'
      fullPath: '/catalog/author/$authorId'
      preLoaderRoute: typeof CatalogAuthorAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogsRouteChildren {
  BlogsBlogIdRoute: typeof BlogsBlogIdRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsBlogIdRoute: BlogsBlogIdRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddRoute: AddRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AuthorsRoute: AuthorsRoute,
  BlogsRoute: BlogsRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  ProfileRoute: ProfileRoute,
  PurchasesRoute: PurchasesRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  ReelsReelIdRoute: ReelsReelIdRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  ReelsIndexRoute: ReelsIndexRoute,
  CatalogAuthorAuthorIdRoute: CatalogAuthorAuthorIdRoute,
  CatalogCourseCourseIdRoute: CatalogCourseCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
